### ISSUE TITLE
Information updating about new notaries from the second round of Notary elections

### ISSUE THREAD

**Issue by laurarenpanda** [filedrive-team/filplus-info#2]
## Notaries Information Upgrade
Update Information about new notaries from the second round of Notary elections on the homepage.

Information about the second round of Notary elections:
https://github.com/filecoin-project/notary-governance/issues/118#issuecomment-874343752

**Comment by dkkapur** [comment]
https://github.com/filecoin-project/notary-governance/commit/fb798c1f261db45059768bbc60218687831d4983
